cmake_minimum_required(VERSION 3.22)
project(Kokkos_GoogleTest CXX)
add_library(gtest gtest/gtest-all.cc)
add_library(GTest::gtest ALIAS gtest)
target_include_directories(gtest PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
set_target_properties(gtest PROPERTIES CXX_STANDARD ${KOKKOS_CXX_STANDARD})
if(ALL_KOKKOS_COMPILER_FLAGS)
  set_target_properties(gtest PROPERTIES COMPILE_FLAGS ${ALL_KOKKOS_COMPILER_FLAGS})
endif()
if(KOKKOS_LINK_OPTIONS)
  set_target_properties(gtest PROPERTIES LINK_FLAGS ${KOKKOS_LINK_OPTIONS})
endif()
find_package(Threads QUIET)
if(TARGET Threads::Threads)
  target_link_libraries(gtest PUBLIC Threads::Threads)
endif()

