FROM nvidia/cuda:9.2-devel

RUN apt-get update && apt-get install -yq \
      wget bc pkg-config tree vim git cmake && \
    rm -rf /var/lib/apt/lists/*

ENV KOKKOS_DIR=/opt/kokkos
ARG KOKKOS_VERSION=2.8.00
RUN KOKKOS_URL=https://github.com/kokkos/kokkos/archive/${KOKKOS_VERSION}.tar.gz && \
    KOKKOS_ARCHIVE=kokkos-${KOKKOS_VERSION}.tar.gz && \
    SCRATCH_DIR=/scratch && mkdir ${SCRATCH_DIR} && cd ${SCRATCH_DIR} && \
    wget --quiet ${KOKKOS_URL} --output-document=${KOKKOS_ARCHIVE} && \
    mkdir -p kokkos && \
    tar -xf ${KOKKOS_ARCHIVE} -C kokkos --strip-components=1 && \
    cd kokkos && mkdir build && cd build && \
    cmake \
        -D CMAKE_INSTALL_PREFIX=${KOKKOS_DIR} \
        -D CMAKE_CXX_COMPILER=${SCRATCH_DIR}/kokkos/bin/nvcc_wrapper \
        -D KOKKOS_ARCH="Volta70;SNB" \
        -D KOKKOS_ENABLE_SERIAL=ON \
        -D KOKKOS_ENABLE_OPENMP=ON \
        -D KOKKOS_ENABLE_CUDA=ON \
        -D KOKKOS_ENABLE_CUDA_LAMBDA=ON \
        .. && \
     make -j4 && make install && \
     rm -r ${SCRATCH_DIR}
