name: github-windows

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}-win-x64
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions: read-all

jobs:
  windows-serial:
    # Serial build on Windows
    name: Serial VS-2022
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: install gtest
      shell: bash
      run: |
        vcpkg install gtest:x64-windows
    - name: configure
      shell: bash
      run: |
        cmake -B build -DBUILD_SHARED_LIBS=ON -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
    - name: build library
      shell: bash
      run: |
        cmake --build build --parallel 4 --config Release
    - name: run tests
      shell: bash
      run: |
        export PATH="$(pwd)/build/core/src/Release:$(pwd)/build/containers/src/Release:$PATH"
        ctest --test-dir build -C Release -j 4 --output-on-failure
